#!/usr/bin/env python3
"""
Bimanual YAM — one-command setup + demo.

    uv sync --extra yam      # install everything (deps pinned in uv.lock)
    uv run yam-setup         # auto-detect cameras → write yam_bimanual.yaml → check CAN
    uv run yam-demo          # setup + run the closed-loop demo

Philosophy: config is DERIVED, not hand-edited. We enumerate the RealSense
cameras and probe CAN for you, so onboarding a new robot is "plug in + run".
Press Ctrl-C ONCE during a run — the connector safely homes the arms + releases
the motors. (A second Ctrl-C force-quits and SKIPS the safe-home.)
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

CONFIG_PATH = Path(__file__).resolve().parent / "yam_bimanual.yaml"
DEFAULT_PROMPT = os.environ.get("REFLEX_YAM_PROMPT", "pack the container")
# Safety: default to dry_run (full pipeline, NO arm motion). Set
# REFLEX_YAM_APPLY=1 to actually drive the arms.
APPLY = os.environ.get("REFLEX_YAM_APPLY", "0") == "1"
MAX_STEPS = int(os.environ.get("REFLEX_YAM_MAX_STEPS", "200"))


def _c(code: str, s: str) -> str:
    return f"\033[{code}m{s}\033[0m"


def detect_cameras() -> dict[str, str]:
    """Enumerate RealSense devices → {top: serial, left: serial, right: serial}.

    The D435 (wider FOV) is the overhead/top cam; the two D405s are the wrists.
    Left/right is assigned arbitrarily — eyeball the stream and swap if needed.
    """
    import pyrealsense2 as rs  # imported here so `yam-setup` errors are clear

    ctx = rs.context()
    d435: list[str] = []
    d405: list[str] = []
    for dev in ctx.query_devices():
        name = dev.get_info(rs.camera_info.name)
        serial = dev.get_info(rs.camera_info.serial_number)
        if "D435" in name:
            d435.append(serial)
        elif "D405" in name:
            d405.append(serial)
    if not d435 or len(d405) < 2:
        raise RuntimeError(
            f"expected 1×D435 + 2×D405, found {len(d435)}×D435 + {len(d405)}×D405. "
            "Check USB connections (lsusb | grep RealSense). If a camera is "
            "wedged, fully unplug all 3 for 30s and replug."
        )
    return {"top": d435[0], "left": d405[0], "right": d405[1]}


CONFIG_TEMPLATE = """\
# AUTO-GENERATED by `uv run yam-setup` — camera serials detected from hardware.
mode: {mode}                 # dry_run = NO arm motion; apply_actions = arms move
max_steps: {max_steps}       # finite → attempts the task then auto safe-homes
control_period_s: 0.2
stop_on_error: true
pipeline_inference: false

target:
  kind: webrtc               # cloud, ~90ms server / ~220ms RTT. No url: the SDK
  timeout_s: 60              # picks the nearest healthy worker (region-aware).
  connect_timeout_s: 60
  state_field: "state"
  instruction_field: "prompt"
  img_size: 256
  extra_payload:
    num_steps: 5

hardware:
  kind: yam_bimanual
  config:
    left:  {{ channel: can1, gripper: linear_4310 }}
    right: {{ channel: can0, gripper: linear_4310 }}
    hz: 25
    zero_gravity_mode: false
    instruction: "{prompt}"
    home_duration_s: 4.0
    chunk_boundary_max_delta: 0.05
    chunk_apply_horizon: 0

cameras:
  top:   {{ kind: realsense, serial: "{top}",   width: 640, height: 480, fps: 30 }}
  left:  {{ kind: realsense, serial: "{left}",  width: 640, height: 480, fps: 30 }}
  right: {{ kind: realsense, serial: "{right}", width: 640, height: 480, fps: 30 }}
"""


def write_config(serials: dict[str, str]) -> None:
    CONFIG_PATH.write_text(
        CONFIG_TEMPLATE.format(
            mode="apply_actions" if APPLY else "dry_run",
            max_steps=MAX_STEPS,
            prompt=DEFAULT_PROMPT,
            **serials,
        )
    )


def can_status() -> dict[str, bool]:
    """True per interface if it's UP with carrier."""
    out: dict[str, bool] = {}
    for iface in ("can0", "can1"):
        try:
            r = subprocess.run(
                ["ip", "-br", "link", "show", iface],
                capture_output=True, text=True, timeout=5,
            )
            out[iface] = "UP" in r.stdout and "NO-CARRIER" not in r.stdout
        except Exception:
            out[iface] = False
    return out


def setup_cli() -> int:
    print(_c("1", "YAM setup — detecting hardware"))
    try:
        serials = detect_cameras()
    except Exception as e:
        print(_c("31", f"  ✗ cameras: {e}"))
        return 1
    for slot, s in serials.items():
        print(f"  ✓ {slot:5} → {s}")
    write_config(serials)
    print(f"  ✓ wrote {CONFIG_PATH.name} (mode={'apply_actions' if APPLY else 'dry_run'})")

    can = can_status()
    for iface, up in can.items():
        print(("  ✓ " if up else "  ! ") + f"{iface} {'UP' if up else 'DOWN'}")
    if not all(can.values()):
        print(_c("33", "  CAN not ready — bring it up (one-time, needs sudo):"))
        print("    sudo ip link set can0 up type can bitrate 1000000")
        print("    sudo ip link set can1 up type can bitrate 1000000")
    print()
    print("  Next: uv run yam-demo   (set REFLEX_YAM_APPLY=1 to move the arms)")
    return 0


def demo_cli() -> int:
    rc = setup_cli()
    if rc != 0:
        return rc
    if not all(can_status().values()):
        print(_c("31", "  ✗ CAN not up — run the two sudo commands above first."))
        return 1
    print()
    mode = "apply_actions (ARMS WILL MOVE)" if APPLY else "dry_run (no motion)"
    print(_c("1", f"YAM demo — {mode}"))
    print(_c("33", "  >>> press Ctrl-C ONCE to stop + safe-home <<<"))
    # reflex connect is the SDK cli (installed via reflex-sdk).
    cmd = ["reflex", "connect", "--config", str(CONFIG_PATH)]
    try:
        return subprocess.call(cmd)
    except FileNotFoundError:
        print(_c("31", "  ✗ `reflex` not found — did `uv sync --extra yam` run?"))
        return 1


if __name__ == "__main__":
    sys.exit(demo_cli() if "--demo" in sys.argv else setup_cli())
